set_property PACKAGE_PIN A12 [get_ports {ad7606c_port_ad_os[0]}]
set_property PACKAGE_PIN A11 [get_ports {ad7606c_port_ad_os[1]}]
set_property PACKAGE_PIN B13 [get_ports {ad7606c_port_ad_os[2]}]
set_property PACKAGE_PIN A13 [get_ports ad7606c_port_ad_convstab]
set_property PACKAGE_PIN B14 [get_ports ad7606c_port_ad_reset]
set_property PACKAGE_PIN A14 [get_ports ad7606c_port_ad_rd]
set_property PACKAGE_PIN C13 [get_ports ad7606c_port_ad_wr]
set_property PACKAGE_PIN E14 [get_ports ad7606c_port_ad_cs]
set_property PACKAGE_PIN E13 [get_ports ad7606c_port_ad_busy]
set_property PACKAGE_PIN B15 [get_ports ad7606c_port_ad_first_data]
set_property PACKAGE_PIN B10 [get_ports {ad7606c_port_ad_data[0]}]
set_property PACKAGE_PIN C11 [get_ports {ad7606c_port_ad_data[1]}]
set_property PACKAGE_PIN D14 [get_ports {ad7606c_port_ad_data[2]}]
set_property PACKAGE_PIN D15 [get_ports {ad7606c_port_ad_data[3]}]
set_property PACKAGE_PIN F11 [get_ports {ad7606c_port_ad_data[4]}]
set_property PACKAGE_PIN F12 [get_ports {ad7606c_port_ad_data[5]}]
set_property PACKAGE_PIN H13 [get_ports {ad7606c_port_ad_data[6]}]
set_property PACKAGE_PIN H14 [get_ports {ad7606c_port_ad_data[7]}]
set_property PACKAGE_PIN G14 [get_ports {ad7606c_port_ad_data[8]}]
set_property PACKAGE_PIN G15 [get_ports {ad7606c_port_ad_data[9]}]
set_property PACKAGE_PIN F10 [get_ports {ad7606c_port_ad_data[10]}]
set_property PACKAGE_PIN G11 [get_ports {ad7606c_port_ad_data[11]}]
set_property PACKAGE_PIN H12 [get_ports {ad7606c_port_ad_data[12]}]
set_property PACKAGE_PIN J12 [get_ports {ad7606c_port_ad_data[13]}]
set_property PACKAGE_PIN J14 [get_ports {ad7606c_port_ad_data[14]}]
set_property PACKAGE_PIN K14 [get_ports {ad7606c_port_ad_data[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports ad7606c_port_ad_convstab]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606c_port_ad_reset]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606c_port_ad_rd]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606c_port_ad_wr]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606c_port_ad_cs]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606c_port_ad_busy]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606c_port_ad_first_data]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606c_port_ad_os[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606c_port_ad_data[*]}]
# set_property DRIVE 12   [get_ports {ad7606c_port_ad_data[*]}]
# set_property SLEW FAST  [get_ports {ad7606c_port_ad_data[*]}]

#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[15]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[14]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[13]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[12]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[11]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[10]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[9]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[8]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[7]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[6]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[5]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[4]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[3]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[2]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[1]}]
#set_property PULLDOWN true [get_ports {ad7606c_port_ad_data[0]}]
#set_property DRIVE 12 [get_ports {ad7606c_port_ad_os[2]}]
#set_property DRIVE 12 [get_ports {ad7606c_port_ad_os[1]}]
#set_property DRIVE 12 [get_ports {ad7606c_port_ad_os[0]}]
#set_property DRIVE 16 [get_ports ad7606c_port_ad_rd]
#set_property DRIVE 16 [get_ports ad7606c_port_ad_cs]
#set_property DRIVE 16 [get_ports ad7606c_port_ad_convstab]



